stages:
  extract_sensors:
    cmd: python -m src.data.spatial_data
    deps:
      - ${data.paths.weather_data}
      - ${data.paths.sensor_data}
      - src/data/utils.py
      - src/data/opentopodata.py
      - src/data/osmdata.py
      - requirements.txt
    outs:
      - ${data.paths.sensors_file}
  create_dataset:
    cmd: python -m src.data.sensors_data
    deps:
      - ${data.paths.sensors_file}
      - src/data/utils.py
      - src/data/sensors_data.py
    outs:
      - ${data.paths.dataset_file}
  spat_cv:
    cmd: python -m experiments.spat_cv
    deps: 
      - src/gp/
      - experiments/spat_cv.py
      - ${data.paths.dataset_file}
    metrics:
      - ${model.spat_cv.result_file}:
          cache: false
    plots:
      - ${model.spat_cv.plot_file}:
          cache: false
  temp_cv:
    cmd: python -m experiments.temp_cv
    deps: 
      - src/gp/
      - experiments/temp_cv.py
      - ${data.paths.dataset_file}
    metrics:
      - ${model.temp_cv.result_file}:
          cache: false
    plots:
      - ${model.temp_cv.plot_file}:
          cache: false
