stages:
  extract_sensors:
    cmd: python -m src.data.spatial_data
    deps:
      - ${data.paths.weather_data}
      - ${data.paths.sensor_data}
      - src/data/utils.py
      - src/data/opentopodata.py
      - src/data/osmdata.py
      - requirements.txt
    outs:
      - ${data.paths.sensors_file}
  create_dataset:
    cmd: python -m src.data.sensors_data
    deps:
      - ${data.paths.sensors_file}
      - src/data/utils.py
      - src/data/sensors_data.py
    outs:
      - ${data.paths.dataset_file}

